name = "stratocumulus"
version = "0.1.1"
target = "javascript"

description = "Gleam Bindings to browser WebSocket client"
licences = ["MIT"]

[[links]]
title = "Sponsor"
href = "https://github.com/sponsors/ghivert"

[repository]
type = "github"
user = "ghivert"
repo = "stratocumulus"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
